import { NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { AppModule } from './app.module';
import { configureApp } from './app.setup';
import { PublicApiModule } from './modules/public-api/public-api.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule, { rawBody: true });

  configureApp(app);

  const swaggerConfig = new DocumentBuilder()
    .setTitle('PulseCRM API')
    .setDescription('PulseCRM backend API documentation')
    .setVersion('1.0')
    .addBearerAuth()
    .build();
  const swaggerDocument = SwaggerModule.createDocument(app, swaggerConfig);
  // /public/v1/* gets its own dedicated document (built below) with an
  // API-key security scheme instead of Bearer, so strip it out here.
  swaggerDocument.paths = Object.fromEntries(
    Object.entries(swaggerDocument.paths).filter(
      ([path]) => !path.startsWith('/public/v1'),
    ),
  );
  SwaggerModule.setup('api/docs', app, swaggerDocument);

  const publicSwaggerConfig = new DocumentBuilder()
    .setTitle('PulseCRM Public API')
    .setDescription(
      [
        'A REST API for integrating external systems (imports, automations, custom dashboards) with your PulseCRM data.',
        '',
        '## Authentication',
        'Every request must include an `X-API-Key` header with a key generated by an Admin from **Settings → API Keys** (`POST /api/v1/api-keys` in the main app). Keys are shown only once at creation — store them securely.',
        '',
        '```',
        'curl https://your-domain.example/public/v1/contacts \\',
        '  -H "X-API-Key: pcrm_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"',
        '```',
        '',
        '## Creating a contact',
        '```',
        'curl -X POST https://your-domain.example/public/v1/contacts \\',
        '  -H "X-API-Key: pcrm_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \\',
        '  -H "Content-Type: application/json" \\',
        '  -d \'{"firstName":"Jane","lastName":"Doe","email":"jane@example.com","ownerId":"<user-id>"}\'',
        '```',
        '',
        '## Rate limiting',
        'Each API key is limited to **100 requests per minute**. Exceeding this returns `429 Too Many Requests`.',
        '',
        '## Scope',
        'All data is scoped to the organization the key belongs to — there is no cross-organization access. This surface has no concept of per-user roles (Rep/Manager/Admin); every key sees and can act on the full organization.',
      ].join('\n'),
    )
    .setVersion('1.0')
    .addApiKey({ type: 'apiKey', name: 'X-API-Key', in: 'header' }, 'X-API-Key')
    .build();
  const publicSwaggerDocument = SwaggerModule.createDocument(
    app,
    publicSwaggerConfig,
    { include: [PublicApiModule] },
  );
  SwaggerModule.setup('public/docs', app, publicSwaggerDocument);

  const port = process.env.PORT ?? 3000;
  await app.listen(port);
}
bootstrap();
